version: '2'
services:

  web:
    image: ansible/awx_web
    container_name: awx_web
    depends_on:
      - redis
      - memcached
      - postgres
    ports:
      - "8052:8052"
    hostname: awxweb
    user: root
    restart: unless-stopped
    volumes:
      - "./config/SECRET_KEY.txt:/etc/tower/SECRET_KEY"
      - "./config/environment.sh:/etc/tower/conf.d/environment.sh"
      - "./config/credentials.py:/etc/tower/conf.d/credentials.py"
      - "./config/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "/tmp/redis_socket:/var/run/redis/:rw"
      - "/tmp/memcached_socket:/var/run/memcached/:rw"
      - "./projects:/var/lib/awx/projects:rw"
      - "./inventories:/var/lib/awx/inventories:rw"
      # - "/etc/pki/ca-trust/source/anchors:/etc/pki/ca-trust/source/anchors:ro"
      # - "ssl_certificate:/etc/nginx/awxweb.pem:ro"
    environment:
      http_proxy: ''
      https_proxy: ''
      no_proxy: ''
  
  task:
    image: ansible/awx_task
    container_name: awx_task
    depends_on:
      - redis
      - memcached
      - web
      - postgres
    user: root
    restart: unless-stopped
    volumes:
      - "./config/SECRET_KEY.txt:/etc/tower/SECRET_KEY"
      - "./config/environment.sh:/etc/tower/conf.d/environment.sh"
      - "./config/credentials.py:/etc/tower/conf.d/credentials.py"
      - "./projects:/var/lib/awx/projects:rw"
      - "/tmp/redis_socket:/var/run/redis/:rw"
      - "/tmp/memcached_socket:/var/run/memcached/:rw"
      # - "/etc/pki/ca-trust/source/anchors:/etc/pki/ca-trust/source/anchors:ro"
      # - "ssl_certificate:/etc/nginx/awxweb.pem:ro"
    environment:
      http_proxy: ''
      https_proxy: ''
      no_proxy: ''
  
  redis:
    image: redis
    container_name: awx_redis
    restart: unless-stopped
    environment:
      http_proxy: ''
      https_proxy: ''
      no_proxy: ''
    command: ["/usr/local/etc/redis/redis.conf"]
    volumes:
      - "./config/redis.conf:/usr/local/etc/redis/redis.conf:ro"
      - "/tmp/redis_socket:/var/run/redis/:rw"
      - "/tmp/memcached_socket:/var/run/memcached/:rw"

  memcached:
    image: "memcached:alpine"
    container_name: awx_memcached
    command: ["-s", "/var/run/memcached/memcached.sock", "-a", "0666"]
    restart: unless-stopped
    environment:
      http_proxy: ''
      https_proxy: ''
      no_proxy: ''
    volumes:
      - "/tmp/memcached_socket:/var/run/memcached/:rw"

  
  postgres:
    image: postgres
    container_name: awx_postgres
    user: root
    ports:
      - "5432"
    restart: unless-stopped
    volumes:
      - "./postgres/data:/var/lib/postgresql/data:Z"
    environment:
      POSTGRES_USER: awx
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: awx
      PGDATA: /var/lib/postgresql/data/pgdata
      http_proxy: ''
      https_proxy: ''
      no_proxy: ''

  
#   metricbeat:
#     image: docker.elastic.co/beats/metricbeat:${ELASTIC_VERSION:-7.5.2}
#     user: root
#     environment:
#       - KIBANA_HOST='${KIBANA_HOST}:5601'
#       - ELASTIC_HOST='${ELASTIC_HOST}:9200'
#       - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME-elastic}
#       - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD-changeme}
#       - AWX_DB_USER=${AWX_DB_USER:-awx}
#       - AWX_DB_PASS=${AWX_DB_PASS:-changeme}
#       - AWX_RABBITMQ_USER=${AWX_RABBITMQ_USER:-guest}
#       - AWX_RABBITMQ_PASS=${AWX_RABBITMQ_PASS:-changeme}
#     configs:
#       - source: metricbeat_config
#         target: /usr/share/metricbeat/metricbeat.yml
#     command: -system.hostfs=/hostfs
#     volumes:
#       - /var/run/docker.sock:/var/run/docker.sock:ro
#       - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
#       - /proc:/hostfs/proc:ro
#       - /:/hostfs:ro
#       - ./metricbeat/dashboards:/usr/share/metricbeat/kibana/7/dashboard:ro
#     deploy:
#       mode: replicated

# configs:
#   metricbeat_config:
#     file: ./metricbeat/config/metricbeat.yml
