  
DATABASE_USER='awx'
DATABASE_NAME='awx'
DATABASE_HOST='postgres'
DATABASE_PORT='5432'
DATABASE_PASSWORD='changeme'
DATABASE_ADMIN_PASSWORD='changeme'
AWX_ADMIN_USER='admin'
AWX_ADMIN_PASSWORD='changeme'